import type { Metadata } from 'next'
import { Heebo } from 'next/font/google'
import './globals.css'

import { Footer,Header } from '../components/index'
// Setup the new Howl.

const inter = Heebo({ subsets: ['hebrew'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>

    <Header></Header>
    <main>
        {children}
        </main>
        <Footer></Footer>
        
        </body>
    </html>
  )
}
